services:  
  wasimancer-server:
    image: k33g/wasimancer:0.0.7
    environment:
      - HTTP_PORT=3001
      - PLUGINS_PATH=./plugins
      - PLUGINS_DEFINITION_FILE=plugins.yml
      - RESOURCES_PATH=./resources
      - RESOURCES_DEFINITION_FILE=resources.yml
      - PROMPTS_PATH=./prompts
      - PROMPTS_DEFINITION_FILE=prompts.yml
      - WASIMANCER_ADMIN_TOKEN=wasimancer-rocks
      - WASIMANCER_AUTHENTICATION_TOKEN=mcp-is-the-way
      #- WASIMANCER_AUTHENTICATION_TOKEN=NO_AUTHENTICATION
      - UPLOAD_PATH=./plugins/bucket
      # All the variables starting with WASM_ are passed as config to the Extism plugin
      - WASM_MESSAGE=wasm plugins are the way
      - WASM_VERSION=0.0.1
    ports:
      - 3001:3001
    volumes:
      - ./resources:/app/resources
      - ./plugins:/app/plugins
      - ./prompts:/app/prompts


