services:

  wasm-workspace:
    build:
      context: .
      platforms:
        #- "linux/amd64"
        - "linux/arm64"
      dockerfile: wasm.Dockerfile
      args:
        - GO_VERSION=1.23.0
        - TINYGO_VERSION=0.35.0
        - NODE_MAJOR=22
        - EXTISM_VERSION=1.6.2
        - USER_NAME=${USER}
    network_mode: "host"   
    volumes:
      - ../..:/workspaces:cached      
    command: sleep infinity

