services:  
  build-plugin-roll-dice:
    image: k33g/tinygo-builder:preview
    volumes:
      - ./roll-dice:/src
    working_dir: /src
    command: >
      tinygo build -scheduler=none --no-debug
      -o wasimancer-plugin-roll-dice.wasm
      -target wasi main.go

  build-plugin-calc:
    image: k33g/tinygo-builder:preview
    volumes:
      - ./calc:/src
    working_dir: /src
    command: >
      tinygo build -scheduler=none --no-debug
      -o wasimancer-plugin-calc.wasm
      -target wasi main.go

  build-plugin-fetch:
    image: k33g/tinygo-builder:preview
    volumes:
      - ./fetch:/src
    working_dir: /src
    command: >
      tinygo build -scheduler=none --no-debug
      -o wasimancer-plugin-fetch.wasm
      -target wasi main.go

  build-plugin-hello:
    image: k33g/tinygo-builder:preview
    volumes:
      - ./hello:/src
    working_dir: /src
    command: >
      tinygo build -scheduler=none --no-debug
      -o wasimancer-plugin-hello.wasm
      -target wasi main.go
